create database ecommerce;
use ecommerce;
show databases;
select * from ecommerce;
show tables;
desc ecommerce;
select * from ecommerce limit 10;
SELECT COUNT(*) AS total_rows FROM ecommerce;
select count(*)as total_rows,count(distinct order_id) as unique_ids from ecommerce;
select order_id,count(*) from ecommerce group by order_id having count(*) >1;

-- Total Sales kitni hui?
select sum(sales) as total_sales from ecommerce;

-- 1. Find total number of orders
SELECT COUNT(DISTINCT order_id) AS total_orders
FROM ecommerce;

-- Find the total sales/revenue generated from all orders.
select round(sum(sales),2) as total_sales from ecommerce;

-- 2. Find the average order value (AOV).
SELECT ROUND(SUM(sales) / COUNT(DISTINCT order_id), 2) AS average_order_value
FROM ecommerce;

-- Q2. Find the total revenue generated by each product category.
select category ,round(sum(sales), 2) as total_revenue from  ecommerce group by category;

-- Find the top 3 product categories based on total revenue.
select category ,round(sum(sales), 2) as total_revenue from  ecommerce group by category order by total_revenue desc limit 3;


-- Find the category with the highest total revenue.
SELECT category,
       ROUND(SUM(sales), 2) AS total_revenue
FROM ecommerce
GROUP BY category
ORDER BY total_revenue DESC
LIMIT 1;

-- Find the total revenue generated by each city.
select city,round(sum(sales), 2) as total_revenue_by_city from ecommerce group by city;

-- Find the top 5 cities based on total revenue.
select city,round(sum(sales), 2) as total_revenue_by_city from ecommerce group by city order by total_revenue_by_city desc limit 5;

-- Find the total number of orders placed by each city.
select city,count(distinct order_id) as total_num_orders from ecommerce group by city;

-- Find the top 5 cities based on the number of orders.
select city,count(distinct order_id) as total_num_orders from ecommerce group by city order by total_num_orders desc limit 5;

-- Find the average sales per order for each city.
SELECT city,ROUND(SUM(sales) / COUNT(DISTINCT order_id), 2) AS average_order_sales
FROM ecommerce group by city;

-- Find the city with the highest average order sales.
SELECT city,ROUND(SUM(sales) / COUNT(DISTINCT order_id), 2) AS average_order_sales
FROM ecommerce group by city order by average_order_sales desc limit 1;

-- Find the total revenue generated by each category and sort it from highest to lowest.
select category , round(sum(sales), 2) as total_revenueby_category from ecommerce group by category order by
total_revenueby_category desc;

-- Find the category having the lowest total revenue.
select category , round(sum(sales), 2) as total_revenueby_category from ecommerce group by category order by
total_revenueby_category asc limit 1;

-- Find the total number of orders placed in each category.
select category ,count(distinct order_id) as total_num from ecommerce group by category;

-- Find the top 2 categories based on the number of orders.
select category ,count(distinct order_id) as total_num from ecommerce group by category order by total_num desc limit 2;

-- Find the average sales per order for each category.
select category,round(sum(sales)/ count(distinct order_id), 2) as average_sales from ecommerce group by category;

-- Find the category having the highest average sales per order.
select category,round(sum(sales)/ count(distinct order_id), 2) as average_sales from ecommerce group by category order by average_sales desc limit 1;

-- Find the product category having the highest average sales amount.
select category,round(avg(sales),2) as avg_sales from ecommerce group by category order by avg_sales desc limit 1;

-- Find the category that generated the highest total sales.
select category,round(sum(sales),2) as highest_sales from ecommerce group by category order by highest_sales desc limit 1;

-- Find the category having the highest number of orders.
select category, count(distinct order_id) as highest_orders from ecommerce group by category order by highest_orders desc limit 1;


--  Find the category that has the highest average sales per order.
select category, round(avg(sales), 2) as highest_avg_sales from ecommerce group by category order by highest_avg_sales desc limit 1;

-- Find the category that generated the highest total revenue.
select category, round(sum(sales), 2) as highest_total_sales from ecommerce group by category order by highest_total_sales desc limit 1;

-- Find the category that has the highest number of unique orders.
select category, count(distinct order_id) as highest_num_order from ecommerce group by category order by highest_num_order desc limit 1;

-- Find the top 5 customers based on their total purchase amount.
SELECT 
    customer_name,
    round(SUM(sales), 2) AS total_purchase
FROM ecommerce
GROUP BY customer_name
ORDER BY total_purchase DESC
LIMIT 5;

-- Find the customer who has placed the highest number of orders.
select customer_name,count(distinct order_id) as highest_orders from ecommerce group by customer_name order by highest_orders desc limit 1;

-- Find the average sales amount for each customer, and show only customers whose average sales is greater than 500.
select customer_name,round(avg(sales),2) as avg_sales from ecommerce group by customer_name having avg_sales > 500;

-- Find the total quantity of products sold for each category.
select category, sum(quantity) as total_qunt from ecommerce group by  category;

-- Find the product that generated the highest total sales.
select product,sum(sales) as highest_total_sales from ecommerce group by product order by highest_total_sales desc limit 1;

-- Find the top 5 products based on total sales revenue
select product,round(sum(sales), 2) as highest_total_sales from ecommerce group by product order by highest_total_sales desc limit 5;

-- Find the product with the highest average sales amount
select product,round(avg(sales), 2) as highest_avg_sales from ecommerce group by product order by highest_avg_sales desc limit 1;

-- Find the top 5 customers based on the number of unique products they purchased.
select customer_name,count(distinct product) as num_uni_pro from ecommerce group by customer_name order by num_uni_pro desc limit 5;

-- Find the top 5 products based on total quantity sold
select product,sum(quantity) as top_quantity from ecommerce group by product order by top_quantity desc limit 5;

-- Find the top 5 products based on the number of unique orders in which they were purchased.
select product , count(distinct order_id) as top_unique_order from ecommerce group by product order by top_unique_order desc limit 5;

-- Find the product with the lowest total sales.
select product,round(sum(sales), 2) as lowest_total_sales from ecommerce group by product order by lowest_total_sales asc limit 1;

-- Find the product with the highest total quantity sold
select product,sum(quantity) as highest_total_qunt from ecommerce group by product order by highest_total_qunt desc limit 1;

-- Find the customer who generated the highest total sales in a single order.
select customer_name,order_id, sum(sales) as order_sales from ecommerce group by customer_name, order_id order by order_sales desc limit 1;

-- Find the average quantity of products purchased per order.
select sum(quantity)/count(distinct order_id) as avg_quantity from ecommerce;

-- Find the top 5 customers based on their total quantity of products purchased.
select customer_name ,sum(quantity) as top_customer_pur from ecommerce group by customer_name order by top_customer_pur desc limit 5;

-- Find the customer who placed the most recent order.
select customer_name ,max(order_date) as most_recent_order from ecommerce group by customer_name order by most_recent_order desc  limIT 1;

-- Find the month with the highest total sales
select month(order_date) as month,round(sum(sales), 2) as high_month_sales from ecommerce group by month(order_date) order by high_month_sales desc limit 1;

-- Find the month with the lowest total sales.
select month(order_date) as month,round(sum(sales), 2) as lowest_month_sales from ecommerce group by month(order_date)
 order by lowest_month_sales asc limit 1;

-- Find the month with the highest number of unique orders.
select month(order_date) as month,count(distinct order_id) as month_high_order from ecommerce group by month(order_date)
 order by month_high_order desc limit 1;
 
 -- Find the month with the lowest number of unique orders.
 select month(order_date) as month,count(distinct order_id) as month_lowest_order from ecommerce group by month(order_date)
 order by month_lowest_order asc limit 1;
 
 -- Find the month with the highest total quantity of products sold.
 select month(order_date) as  month,sum(quantity) as high_qunt_month from ecommerce group by month(order_date) order by high_qunt_month desc limit 1; 
 

-- Find the month with the lowest total quantity of products sold.
select month(order_date) as  month,sum(quantity) as low_qunt_month from ecommerce group by month(order_date) order by low_qunt_month asc limit 1; 
 
 -- Find the average sales amount for each month
 select month(order_date) as month,round(avg(sales), 2) as avg_sales from ecommerce group by month(order_date) ;
 

-- Find the average order value (AOV) for each month.
select month(order_date) as month,round(sum(sales)/count(distinct order_id), 2) as avg_order_value from ecommerce group by month(order_date) ;

--  Find the month with the highest average order value (AOV).
select month(order_date) as month,round(sum(sales)/count(distinct order_id), 2) as avg_order_value from ecommerce group by month(order_date)
order by avg_order_value desc limit 1 ;

-- Find the top 5 customers based on their highest single-order value
SELECT 
    customer_name,
    MAX(order_sales) AS highest_single_order
FROM (
    SELECT 
        customer_name,
        order_id,
        SUM(sales) AS order_sales
    FROM ecommerce
    GROUP BY customer_name, order_id
) AS t
GROUP BY customer_name
ORDER BY highest_single_order DESC
LIMIT 5;

-- Find customers who have placed more than 3 unique orders.
select customer_name, count(distinct order_id) as placed_order from ecommerce group by customer_name having placed_order >3;

-- Find the percentage of total sales contributed by each product category.
select category,round(sum(sales)*100 /sum(sum(sales)) over(),2) as sales_precentage from ecommerce group by category;

-- Find the percentage of total quantity sold contributed by each product category.
select category,round(sum(quantity)*100 / sum(sum(quantity)) over(),2) as quantity_percentage from ecommerce
group by category;

-- Find the percentage of total orders contributed by each product category.
select category,round(count(distinct order_id)*100 / sum(count(distinct order_id)) over(),2) as order_percentage from ecommerce
group by category;

-- Find the customer who has purchased products from the highest number of different categories.
select customer_name,count(distinct category) as high_num_cate from ecommerce group by customer_name order by high_num_cate desc limit 1;

-- Find the product category with the highest average quantity per order.
select category , round(sum(quantity)/count(distinct order_id),2) as high_avg_qunt from ecommerce group by category order by high_avg_qunt desc  limit 1;


-- Find the top 5 customers based on their average quantity purchased per order.
select customer_name , round(sum(quantity)/count(distinct order_id),2) as high_avg_qunt from ecommerce group by customer_name 
order by high_avg_qunt desc  limit 5;

-- Find customers whose total sales are greater than the average total sales of all customers.
SELECT 
    customer_name,
    SUM(sales) AS total_sales
FROM ecommerce
GROUP BY customer_name
HAVING SUM(sales) > (
    SELECT AVG(total_sales)
    FROM (
        SELECT 
            customer_name,
            SUM(sales) AS total_sales
        FROM ecommerce
        GROUP BY customer_name
    ) AS customer_totals
);

-- Find the products whose total sales are greater than the average total sales of all products.
select product,round(sum(sales) ,2) as total_sales from ecommerce group by product having total_sales >
(select avg(total_sales) from
(select product, sum(sales) as total_sales from ecommerce group by product)
as product_total);

-- Find the categories whose total sales are greater than the average total sales of all categories.
select category,round(sum(sales) ,2) as total_sales from ecommerce group by category having total_sales >
(select avg(total_sales) from
(select category, sum(sales) as total_sales from ecommerce group by category)
as category_total);

-- Find the customers who have placed more orders than the average number of orders placed by all customers.
select customer_name,count(distinct order_id) as total_num from ecommerce group by customer_name having total_num >
(select avg(total_num) from
(select customer_name, count(distinct order_id) as total_num from ecommerce group by customer_name)
as customer_total_num);

-- Find the top 3 products by revenue within each category.
select * from
(select category,product,round(sum(sales),2)as total_revenue,dense_rank() over(partition by category order by sum(sales) desc)as rnk
 from ecommerce group by category,product)
t where rnk <=3;

-- Find the top 3 customers in each city based on their total sales.
select * from
(select customer_name,city,round(sum(sales),2) as total_sales,dense_rank() over(partition by city order by sum(sales) desc) as rnk 
from ecommerce group by customer_name,city)
t where rnk <=3 ;

-- Find all customers and classify them based on their total number of orders:
-- 1 order → One-Time),(2–3 orders → Regular),(4+ orders → Frequent)
select customer_name,count(distinct order_id) as total_num_order,
case
when count(distinct order_id)  >=4 then 'Frequent'
when count(distinct order_id)  >=2 then 'Regular'
else 'One-Time'
end as Order_Group
from ecommerce group by customer_name;

-- Find the category that generated the highest revenue in each city.
select * from
(select category,city,round(sum(sales),2) as highest_revenue,row_number() over(partition by city order by sum(sales) desc) as rnk 
from ecommerce group by category,city)
t where rnk = 1 ;